### ISSUE TITLE
Remove homolog parsing from loader scripts

### ISSUE THREAD

**Issue by christabone** [alliance-genome/agr#136]
We won't need to index homologs from Panther for 0.3.0 or 0.6.0. DIOPT will eventually be the source of orthologs as soon as we can sort out the loading issues.

**Comment by khowe** [comment]
The ortholog WG would like to complement the DIOPT/multiple-method view with another view based  a single method (e.g. PANTHER) - to provide additional resources such as trees and multiple alignments. This is planned for 0.6. 

If we go down the path of least resistance and use PANTHER, the loading scripts will be needed for 0.6 (although perhaps in modified form)

**Comment by christabone** [comment]
Thanks for the clarification Kevin. 

DIOPT has its own version of Panther data -- I believe we should still remove this current version from the index as it's loading from a separate flat file. Loading two versions of Panther may be confusing. Has the ortho group discussed this issue?

**Comment by khowe** [comment]
That specific issue has not been discussed, no. We assumed that in order to link to PANTHER trees (or multiple alignments), each gene would need to be associated with a PANTHER homology group, which the DIOPT data does not provide (it only includes a link to an orthologous gene via PANTHER). 

However, it seems that PANTHER trees/alignments can be fetched via a gene id as an alternative to a homology group id. Which would not require any additional data in the index. Although might lead to "interesting" inconsistencies whereby the tree for a (say) worm gene shows orthology to a (say) fly gene, but that orthology is not shown in the DIOPT table (due to different versions of PANTHER). Something for us to discuss. 

But anyway, I think yes, it is possible to integrate/display PANTHER tree/alignment data without loading it into ES. So removing the PANTHER-only load is fine.

**Comment by christabone** [comment]
OK, thanks again Kevin!

Also as an FYI -- the "removal" should only require commenting out a line or two. It can be easily reversed and should speed up the whole indexing process.
