### ISSUE TITLE
Human Gene Reports show RGD as primary source

### ISSUE THREAD

**Issue by christabone** [alliance-genome/agr#155]
![image](https://cloud.githubusercontent.com/assets/3584662/23240678/bf207a32-f93c-11e6-81ae-ab5cd4c49026.png)

Would this be a frontend or backend bug? The web address looks good (HGNC:132), so is it something in the React code?

**Comment by christabone** [comment]
Ah, it's probably the dataProvider field in metaData from the JSON. I will look and report back shortly.

**Comment by christabone** [comment]
Yep, OK, so the dataProvider is flagged as RGD, which is technically correct. Perhaps some logic to make this a Human Gene Report when the taxonid is 9606? 

`  "dataProvider": "RGD"` 
`  "dateProduced": "2017-02-21T15:01:04-06:00" `

**Comment by paaatrick** [comment]
Yeah, I was just talking to @sierra-moxon about this yesterday. There are probably a collection of little, weird things caused by the fact that the gene record's dataProvider is not one-to-one with species. So, yeah, we could special case it in the front-end code, especially for now. Maybe that's the best we can do, or maybe there's a better back-end solution. Not sure.

**Comment by christabone** [comment]
A front-end solution would be fantastic, if you could pull if off for the imminent 0.3.0 internal release.

It's an interesting point about dataProvider vs species. Moving forward, there are cases such as UniProt, EMBL, _etc_ which we have as dataProviders but they aren't tied to a single species. It's probably best to go by species id (unless we have cases where multiple species are grouped into a single MOD). That's my humble opinion on the matter.

**Comment by khowe** [comment]
@christabone I agree. Although we included a "dataProvider" stanza in the JSON, I (at least) regarded this as internal tracking data, and not for display on the website. 

For the website, it's more appropriate to have an "authoritative source", probably at the per-species level. And since we are using HGNC id as primary for human genes, HGNC would be the de facto authoritative source for the human gene entries.
