### ISSUE TITLE
Disease terms should be coming from DO not OMIM

### ISSUE THREAD

**Issue by srengel** [alliance-genome/agr#161]
http://disease-ontology.org

**Comment by christabone** [comment]
Hi Stacia,

Is this in regards to the disease on the search result list? The data is left over from the prototype. There was discussion to remove it if necessary. 

We won't have real DO data in 0.3.0 (only the hard-coded example on the Gene Report). Should we remove the OMIM disease info from the search results?

@sierra-moxon @a8wright

**Comment by christabone** [comment]
It looks like we are removing these for now. I will make the necessary changes to the loaders.

Cynthia Smith
1:45 PM (1 minute ago)

to me 
Hi Chris 
We have a consensus - please proceed. 
Cynthia
——————————————————
Cynthia L. Smith, PhD
Research Scientist 
Mouse Genome Informatics
The Jackson Laboratory
600 Main Street
Bar Harbor, Maine 04609  USA
1-207-288-6663 t | 1-207-288-6131 f
Cynthia.Smith@jax.org
www.informatics.jax.org
www.findmice.org
www.CrePortal.org

Hi Cynthia,

Thank you for the response. Can I take your reply as consensus for the disease group? Please let me know and I'll begin making the necessary changes.

Best,
Chris

On Thu, Feb 23, 2017 at 1:02 PM, Cynthia Smith <Cynthia.Smith@jax.org> wrote:
I would remove the OMIM disease terms since this will not be the standard. We don’t want to show something that will not be present in the next iteration. 

From: alliance-disease <alliance-disease-bounces@lists.stanford.edu> on behalf of Stacia R Engel <stacia@stanford.edu>
Date: Thursday, February 23, 2017 at 12:34 PM
To: "alliance-disease@lists.stanford.edu" <alliance-disease@mailman.stanford.edu>
Cc: Christopher Tabone <ctabone@morgan.harvard.edu>
Subject: [alliance-disease] Fwd: [alliance-genome/agr] Disease terms should be coming from DO not OMIM (#161)

Question for Disease team:  Should the Technical team remove the OMIM disease info from the search results?

**Comment by christabone** [comment]
@kevinschaper @paaatrick Do we have time to remove disease from the UI or is that not possible? Preventing it from loading is pretty straightforward.

**Comment by srengel** [comment]
@christabone this mushy ambiguous language makes me nervous! "remove disease from the UI"

to clarify, it's the OMIM terms in the search results.  NOT the hard-coded disease table mockup on the gene pages.

**Comment by christabone** [comment]
Ha! Sorry. I'l clarify. :) If you read from the top it makes sense (with the other posts and the title of the issue).

**Comment by srengel** [comment]
oh totally, i get that, and have been reading from the top (i started this ticket myself ;), but does everyone read all text? not under the best of circumstances.  plus now there is so much info flying around, and so many people involved - clarity is key!
