### ISSUE TITLE
ES library isn't successfully mocked in integration tests

### ISSUE THREAD

**Issue by kevinschaper** [alliance-genome/agr#240]
The mock patch for Elasticsearch changed from `@mock.patch('src.server.es.search')` to `@mock.patch('src.dao.elasticsearch_dao.ElasticSearchDAO.es.search')` in https://github.com/alliance-genome/agr/commit/ea0fa77e824e64b4f3421ae9baf4a925e5f1f476, but hasn't work since the search service was refactored.

I added `test_mock_es` which only looks for whether the mock method was successfully called, and will avoid data-mismatch red herrings that show up when a real ES response comes back that doesn't match what's expected from the mock response.

**Comment by oblodgett** [comment]
Trail 1: Made the ES variable static in the dao file to see if that would change anything... nope.

Trail 2: Reverted the code from: 853c4e58bedc61e335a824d6f944d59d49391bcd and put the ES back into the server.py. Pointed the mock back to the way it was before: @mock.patch('src.server.es.search') and it still fails same errors.

So... I guess I don't know where it goes from here?

**Comment by kevinschaper** [comment]
It worked before https://github.com/alliance-genome/agr/commit/853c4e58bedc61e335a824d6f944d59d49391bcd, that refactor is where the tests stopped working.  I went back through to check specifically, https://github.com/alliance-genome/agr/commit/80342eb911e13440083a564406b6842056bccc1b is the last revision that passes the tests, and they stop working at https://github.com/alliance-genome/agr/commit/013e7d07028a2ab472aacf69df26691ab31947d8

(sometimes I miss sequential commit numbers from svn.. )

Maybe remove some of that service layer architecture, at least for the search calls that are being tested with mocking?   What would you have done if the python tests had been running in TravisCI at the time and put a big red error on PR #98 ?  

The other direction to go is to skip the mocking for ES and move to requiring that ES is running and populating an index to run tests against, but that's probably a much bigger task.

**Comment by oblodgett** [comment]
Had the tests been running in TravisCI, they would have failed long before #98 because the environment variable were not being passed to the test-py at this time, so they broke before #98.

Ok so I have committed to he branch the code to put the ES back in the server.py, and pointed the test_search to use "src.server.es.search" the test seems to work python wise but fail ES wise? I don't know enough about ES in order to fix these. Im going to make the commit to the branch if this doesn't work than I will just revert the commit. If you can fix the tests, I will the proceed with the refactor knowing that the tests run, and we can just do it all on this branch until its totally fixes.

Commit: 00b0614d402839195e3993493e5521cd8bd435e9
